### ISSUE TITLE
FR - Choose events for Auto shutdown 

### ISSUE THREAD

**Issue by daved3luxe** [vitormhenrique/OctoPrint-Enclosure#148]
The Temperature / Humidity Control Auto Shutdown will not work if you cancel a printjob or the printer disconnects. Auto Shutdown is activated. Can you adjust that?

**Comment by vitormhenrique** [comment]
That is by design, when the printer is cancel it will run the scripts to automatically "turn off" all the gpios that you have marked.  Many users use it like that, if you have fans, lights, and the printer fail, cancel, they will turn those off.
If you want to have control when the auto-shutdown is activated that is a feature enhancement. And as I said previously I'm not changing or adding features for the plugin on a near feature, last release took me 2 months of coding and I'm working on new projects now, I'll consider for next release, but I it will not be on my top priority.

**Comment by vitormhenrique** [comment]
Please confirm if my comment is what you expected and I'll update this to a feature enhancement.

**Comment by vitormhenrique** [comment]
@daved3luxe could you please confirm that what you expected is what I described on my initial comment?

**Comment by daved3luxe** [comment]
Sorry, Yes that is what I mean.

**Comment by vitormhenrique** [comment]
I'll change it for a feature enhancement.

**Comment by vitormhenrique** [comment]
Added on https://github.com/vitormhenrique/OctoPrint-Enclosure/releases/tag/4.09
