### ISSUE TITLE
MOAR IO!

### ISSUE THREAD

**Issue by mcmasterp** [vitormhenrique/OctoPrint-Enclosure#15]
Bet you saw this coming. I need one more io at least lol. I ended up putting hotend, ramps, and an eclosure fan on relays, plus the lights and I'm maxed out. I holding out hope for temp triggers some point down the line so I am installing the fire supression soleniod setup now since I have the parts ready.

**Comment by vitormhenrique** [comment]
I'm already coding the new plugin, spoiler alert: temperature triggers, and as many io as you want..  basically I'm changing the entire software architecture and allowing creating as many inputs and outputs as you want...

It is going to take few more days because I'm also working on my arcade machine.

**Comment by mcmasterp** [comment]
NICE! thank from everyone.

also, did you say arcade???? my best maker build to date is a bartop for my father in law
[https://hackaday.io/project/13069-murphcade](url)

Got a link to the project?

**Comment by vitormhenrique** [comment]
Implemented on version 3.0 that is on dev branch right now, if you want to test it out uninstall the current plugin and install it again manually using the development branch. I still need to do more testing, all architecture of the software changed, so it might have few bugs.
 https://github.com/vitormhenrique/OctoPrint-Enclosure/archive/dev.zip
