### ISSUE TITLE
Auto Shutdown before gcode commands execute

### ISSUE THREAD

**Issue by zeroprime790** [vitormhenrique/OctoPrint-Enclosure#191]
Hello,

Recently I installed a relay to control my printers power with octoprint. I enabled the auto shutdown but the enclosure plugin shuts down the printer before the "After print job completes" gcodes have a chance to be executed. As result the hotend remains in the last position, touching the print and melting it.
 
**To Reproduce**
Add output
Select Regular IO
Enable Auto Shutdown
Start a print

Is it possible to run the gcode commands before the auto shutdown is triggered?

![2018-09-25 13_03_14-window](https://user-images.githubusercontent.com/16868447/46007727-6b878780-c0c3-11e8-9d64-ec56f1226e4f.png)
![2018-09-25 13_02_57-window](https://user-images.githubusercontent.com/16868447/46007728-6b878780-c0c3-11e8-8a64-14390028cf85.png)

**Comment by vitormhenrique** [comment]
Do you have the plugin updated?
You should be able to create delays on the shutdown.

<img width="697" alt="screen shot 2018-09-25 at 6 52 08 am" src="https://user-images.githubusercontent.com/3967383/46012712-b5ef1100-c08f-11e8-87cb-e8191675bb05.png">

Another way to fix the issue is to actually shutdown the printer by using the enclosure specific g-code commands at the end of your custom g-code.

**Comment by zeroprime790** [comment]
I see, can you please specify the format? If I want to delay the shutdown for 5 minutes, I will just enter the number 5 there? Or 5 means five hours?

**Comment by zeroprime790** [comment]
Ok, I get it now. Thank you for your help 👍
