### ISSUE TITLE
Simple RGB strip led (color controle)

### ISSUE THREAD

**Issue by devildant** [vitormhenrique/OctoPrint-Enclosure#222]
Hello,
I have standard RGB led strip, and I wish I could change the color of these since your plugin enclosure.
in my research I found this tutorial, but it is necessary to connect the band led to 3 gpio for the RGB (see link and diagram below)
would it be possible to integrate this option in enclosure?
an option led strip with a color picker :)
![1_r30x-br2krpmm11rt-b4mq](https://user-images.githubusercontent.com/8700106/53360043-d2d88a80-3934-11e9-9b6c-53cf4d5bd909.png)
https://medium.com/@danidudas/how-to-connect-rgb-strip-led-lights-to-raspberry-pi-zero-w-and-control-from-node-js-70ddfec19f0b

**Comment by vitormhenrique** [comment]
Very few people use those strips, as "smart" LED's (like neopixel) are really cheap now, especially because RGB strips require external transistors to drive them. so I do not plan to integrate this to the enclosure plugin. 
You can add three PWM outputs and control each color individually already, and if you want, create gcodes buttons with pre defined colors, but I'm not going to implement a color picker for it.
That being said the project is open source, anyone can clone the repository and make the changes if more people are interested enough.

**Comment by devildant** [comment]
Ok, 
by uninstalling and reinstalling your plugin, I found an option led strip, and it seems to work with the module below, I should be able to use my led strip. I have good? :)

https://fr.aliexpress.com/item/Full-color-RGB-LED-Strip-Driver-Module-For-Arduino-Can-Be-Cascaded-Blue-Black-Hot-New/1831927656.html

**Comment by vitormhenrique** [comment]
As I said, using is one thing, you can use it, but it will not offer a "color picker"  as it does for neopixel control.

**Comment by devildant** [comment]
mmm ok, 
I looked at the option available with the strip led there is however a color picker.
![image](https://user-images.githubusercontent.com/8700106/53362708-11714380-393b-11e9-90a8-a02bc6ac6301.png)
I made this request because I already have a led strip, and the price of neopixel is relatively high ($ 70 for 4 meters, yes I have a large enclosure)
thank you in any case for answering me

**Comment by vitormhenrique** [comment]
neopixels are really bright, I bet that 1 strip is more than enough. It can probably illuminate a whole room.
using 3 pwm outputs on each "color"  of your strip would work on your setup with your strip.

**Comment by devildant** [comment]
ok thx :)
