### ISSUE TITLE
Filament box %RH control

### ISSUE THREAD

**Issue by elfhelmp** [vitormhenrique/OctoPrint-Enclosure#58]
This is an enhancement request... do you know how some people use boxes in which they store the filament even during printing to avoid moisture entering their filaments? In regions where RH is >60%, this is an almost indispensable.  I was thinking if you could add some extensions to this plugin for a second temp/humidity sensor that can go inside that outer box and control one of the relays on the relay board to turn on/off a heat pad or an incandescent bulb to heat up the filament box up to say 50 degrees and 20% humidity then stop and repeat this every, say, 4 hours... I'd definitely make a use of it.

**Comment by vitormhenrique** [comment]
I get where you are coming from but the problem is that the plugin is only "active" while printing, for safety reasons. 
I don't want to keep heating and monitoring temperature if the printer is off. Turning heaters on requires being present / near the printer to react. Especially if you are using cheap Chinese relays. The overhead of linux and the amount of stuff that could go wrong make this a hazard.
I would suggest creating a small enclosed heater / monitor with an arduino. Outside the plugin. Arduino (micro controllers) can read and react to  anything much faster, and conceptually, the filament enclosure / temperature reading / monitoring could be a solution outside octoprint. So even if you shutdown your PI. your filament will stay perfect.
